version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: redis
    versions:
    - 3.1.2
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: husky
    versions:
    - 4.3.8
    - 5.0.9
    - 5.1.0
    - 5.1.1
    - 5.1.2
    - 5.1.3
    - 5.2.0
  - dependency-name: pino-pretty
    versions:
    - 4.4.0
    - 4.5.0
    - 4.6.0
    - 4.7.0
  - dependency-name: "@commitlint/config-conventional"
    versions:
    - 12.0.0
    - 12.0.1
  - dependency-name: "@commitlint/cli"
    versions:
    - 12.0.0
    - 12.0.1
  - dependency-name: "@google-cloud/logging-winston"
    versions:
    - 4.0.3
  - dependency-name: helmet
    versions:
    - 4.4.1
  - dependency-name: lint-staged
    versions:
    - 10.5.3
  - dependency-name: cassandra-driver
    versions:
    - 4.6.1
