version: '3'
services:
  redis:
    image: redis
    ports:
      - '6379:6379'
  cassandra:
    image: cassandra
    ports:
      - '9042:9042'
    healthcheck:
      test:
        [
          'CMD',
          'cqlsh',
          '-u cassandra',
          '-p cassandra',
          '-e "describe keyspaces"',
        ]
      interval: 5s
      timeout: 5m
      retries: 10
    volumes:
      - './scripts/cassandra-init.sh:/cassandra-init.sh'
    command: 'sh /cassandra-init.sh'
  ocurl:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - redis
      - cassandra
    links:
      - cassandra
    restart: always
    healthcheck:
      test: ['CMD', 'curl -f', 'localhost:3000/health']
      interval: 5s
      timeout: 1m
      retries: 10
