version: '3'
services:
  redis:
    image: redis
    #ports:
    #  - '6379:6379'
    #volumes:
    #  - '$PWD/redis.conf:/usr/local/etc/redis/redis.confi'
    # command: redis-server /usr/local/etc/redis/redis.conf 
  postgres:
    image: postgres
    restart: always
    #ports:
    #  - '5432:5432'
    volumes:
      - './data/postgres:/var/lib/postgresql/data'
    environment:
      - POSTGRES_USER=ocurl_d
      - POSTGRES_PASSWORD='secretpassword'
  ocurl:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - redis
      - postgres
    links:
      - postgres
      - redis
    restart: always
    environment:
      - PORT=3000
      - PGUSER=ocurl_d
      - PGPASSWORD='secretpassword'
      - PGHOST=postgres
      - PGPORT=5432
    volumes:
      - ${GOOGLE_APPLICATION_CREDENTIALS}:${GOOGLE_APPLICATION_CREDENTIALS}
